### ISSUE TITLE
Small note on tp-link-t1600g-28ps fan-swap post

### ISSUE THREAD

**Issue by zeroZshadow** [calvinbui/calvin.me#16]
Post: https://github.com/calvinbui/calvin.me/blob/master/posts/2019-01-04-tp-link-t1600g-28ps-fan-swap/index.md

Just wanted to say thanks for this post!
I've recently bought a similar switch, the `TL-SG2428P`, and was able to adapt this guide to replacing it's fans for quieter ones.

I did want to ask if a small note could be added to the post for future readers.

The noctua fans, while quieter, are a significant step down in cooling power over the original sunon fans included.
Going from 8200 RPM to 5000 RPM, with quite the drop in airflow and static pressure. Further so if the silencing adapters are used.
This might be problematic for switches in already warm enclosed spaces or that are under load.

Secondly, some units have a "fan status" led, which will start complaining once you swap the fans. As far as i've seen, the led can just be ignored.

Thanks!

**Comment by kraduk** [comment]
what spec were the replacement fans?

**Comment by zeroZshadow** [comment]
I installed 2 `Noctua NF-A4x20 FLX`

**Comment by erustyrannus** [comment]
Hello, this is an old post but, I just got this switch on a second hand deal, do you still have this device? Are the noctua fans a good replacement? Meaning, is your device still alive? I was thinking of maybe replacing the thermal compound as well, do you see this as a doable / beneficial thing?

Any input is appreciated, thanks for documenting this. BTW

Edit: Looks like it is stable enough, I have found the post below on reddit that linked your guide and the user has been running it for two years with the noctua fans: https://www.reddit.com/r/TPLink_Omada/comments/nm952k/comment/kcl7f7z/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by Nico83500** [comment]
Hi, I'm going to do the swap but why do we need to invert pin 1 and 3 ? What if we don't switch both ? Thank you.
